name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ '*' ]


env:
  working-directory: Sources
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  dotnet-version: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet-version }}

    - name: Restore dependencies
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet restore

    - name: Build
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet build -c Release --no-restore --verbosity normal

    - name: Test
      run:
        working-directory: ${{ env.working-directory }}
      run: dotnet test -c Release --no-build --verbosity normal